name: Deploy to GitHub Pages

on:
  push:
    branches: [master, deploy]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Clean npm cache and node_modules
        run: |
          rm -rf node_modules
          rm -f package-lock.json
          npm cache clean --force

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          force_orphan: true
          commit_message: "Deploy to GitHub Pages"
          keep_files: false
          cname: "algoforge.tech"
